#1
sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Pin 1.18.1 until 1.19.1 fixes git metadata
  - conda install python=$TRAVIS_PYTHON_VERSION conda-build=1.18.1 nose
  - conda info -a
  - python setup.py install

script:
  - nosetests

branches:
  only:
    - master
